Add new custom ollama model, change base models, improve ask functions

diff --git a/bashrc_extension b/bashrc_extension
--- a/bashrc_extension
+++ b/bashrc_extension
@@ -521,6 +521,8 @@ ask() {
     prompt="${@:2}"
     log_file_path="/tmp/ollama_prompt_outputs/$1_outputs.md"
 
+    mkdir -p $(dirname "$log_file_path")
+
     if ! pacman -Q ollama &>/dev/null
     then
         echo "[ERROR] You need to install ollama first"
@@ -528,16 +530,30 @@ ask() {
         return 1
     fi
 
-    if ! systemctl is-active ollama &>/dev/null
+    ollama serve &>/dev/null &
+    OLLAMA_PID=$!
+    clear
+
+    EXIT_MESSAGE="* (hint) Run \`ask_log $model\` to open this conversation in $EDITOR"
+
+    for sig in RETURN EXIT SIGHUP SIGINT SIGQUIT SIGTERM SIGABRT SIGUSR1 SIGUSR2; do
+    trap \
+        'kill $OLLAMA_PID &>/dev/null && echo -e "Finished...Stopped Server\n  $EXIT_MESSAGE"' \
+        "$sig" &>/dev/null
+    done
+
+    echo -n "Starting Ollama Server..."
+    sleep 1 # Give server time to start
+
+    if ! ollama list &> /dev/null
     then
-        echo "[ERROR] You need to start the ollama service first"
-        echo -e "\t* (hint) run 'sudo systemctl enable --now ollama'"
+        echo -e "\n[ERROR] Ollama server not running... this shouldn't happen"
         return 1
     fi
 
     if ! ollama list | grep "$model" &>/dev/null
     then
-        echo "[ERROR] Model '$model' doesn't exist"
+        echo -e "\n[ERROR] Model '$model' doesn't exist"
         echo -e "\t* (hint) Run 'ollama list' to see available models"
         return 1
     fi
@@ -556,6 +572,14 @@ ask() {
     done | tee -a "$log_file_path" | bat --paging=always --style=plain --language=markdown
 
     echo "---" >> "$log_file_path"
+}
+
+ask_file() {
+    model="$1"
+    file="$2"
+    prompt="${@:3}"
+
+    ask "$model" "$(cat <(echo -e "$prompt\n\n") $file)"
 }
 
 ask_log() {
